#pragma once

/// Include

#include "int/abs.cpp"
#include "int/log_log2_log10_ln.cpp"
#include "int/mod.cpp"
#include "int/pow_sqrt_exp_exp2.cpp"
#include "float/abs.cpp"
#include "float/floor_ceil_round.cpp"
#include "float/log_log2_log10_ln.cpp"
#include "float/mod.cpp"
#include "float/pow_sqrt_exp_exp2.cpp"
#include "angle/abs.cpp"
#include "angle/arcsin_arccos_arctan_arccot_arcsec_arccsc.cpp"
#include "angle/mod.cpp"
#include "angle/sin_cos_tan_cot_sec_csc.cpp"
#include "complex/abs_norm.cpp"
#include "complex/conj.cpp"
#include "complex/floor_ceil_round.cpp"
#include "complex/log_log2_log10_ln.cpp"
#include "complex/pow_sqrt_exp_exp2.cpp"
#include "polar/abs_norm.cpp"
#include "polar/conj.cpp"
#include "polar/log_log2_log10_ln.cpp"
#include "polar/pow_sqrt_exp_exp2.cpp"
#include "std/common_type.cpp"
#include "std/numeric_limits.cpp"
